<?php
$data = array (
  0 => 
  array (
    'cat_id' => '1',
    'cat_name' => '家具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '2',
    'cat_name' => '建材',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '3',
    'cat_name' => '卧室家具',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '10',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '4',
    'cat_name' => '客厅家具',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '10',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '5',
    'cat_name' => '餐厅家具',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '6',
    'cat_name' => '儿童房家具',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '7',
    'cat_name' => '书房家具',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '9',
    'cat_name' => '小件家具',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '办公家具',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '10',
    'cat_name' => '墙地面',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '12',
    'cat_name' => '厨房卫浴',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '10',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '灯饰照明',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '14',
    'cat_name' => '生活电器',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '15',
    'cat_name' => '装修辅材',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '13',
    'cat_name' => '家装五金',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '16',
    'cat_name' => '床',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '39',
  ),
  16 => 
  array (
    'cat_id' => '17',
    'cat_name' => '床垫',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '54',
  ),
  17 => 
  array (
    'cat_id' => '18',
    'cat_name' => '衣柜',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '33',
  ),
  18 => 
  array (
    'cat_id' => '19',
    'cat_name' => '床头柜',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  19 => 
  array (
    'cat_id' => '21',
    'cat_name' => '定制衣柜',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '26',
    'cat_name' => '卧室套装',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => '27',
  ),
  21 => 
  array (
    'cat_id' => '23',
    'cat_name' => '妆台镜/妆凳',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '13',
  ),
  22 => 
  array (
    'cat_id' => '24',
    'cat_name' => '穿衣镜/衣帽架',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  23 => 
  array (
    'cat_id' => '25',
    'cat_name' => '床尾凳',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '22',
    'cat_name' => '斗柜',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
  ),
  25 => 
  array (
    'cat_id' => '35',
    'cat_name' => '花架/装饰架',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  26 => 
  array (
    'cat_id' => '32',
    'cat_name' => '屏风',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  27 => 
  array (
    'cat_id' => '29',
    'cat_name' => '电视柜',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '63',
  ),
  28 => 
  array (
    'cat_id' => '36',
    'cat_name' => '客厅套装',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '14',
  ),
  29 => 
  array (
    'cat_id' => '33',
    'cat_name' => '休闲椅/凳',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '鞋柜',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '22',
  ),
  31 => 
  array (
    'cat_id' => '27',
    'cat_name' => '沙发',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '67',
  ),
  32 => 
  array (
    'cat_id' => '34',
    'cat_name' => '间厅/玄关柜',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '15',
  ),
  33 => 
  array (
    'cat_id' => '31',
    'cat_name' => '酒柜/装饰柜',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  34 => 
  array (
    'cat_id' => '28',
    'cat_name' => '茶几/边桌',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '35',
  ),
  35 => 
  array (
    'cat_id' => '39',
    'cat_name' => '餐厅套装',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
  ),
  36 => 
  array (
    'cat_id' => '40',
    'cat_name' => '餐边柜',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '餐桌',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '17',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '餐椅',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  39 => 
  array (
    'cat_id' => '99',
    'cat_name' => '儿童卧室套装',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
  ),
  40 => 
  array (
    'cat_id' => '45',
    'cat_name' => '书桌/电脑台',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  41 => 
  array (
    'cat_id' => '42',
    'cat_name' => '儿童床垫',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  42 => 
  array (
    'cat_id' => '46',
    'cat_name' => '儿童椅',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '儿童床头柜',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  44 => 
  array (
    'cat_id' => '98',
    'cat_name' => '儿童书房套装',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  45 => 
  array (
    'cat_id' => '47',
    'cat_name' => '儿童柜类',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  46 => 
  array (
    'cat_id' => '44',
    'cat_name' => '儿童衣柜',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '13',
  ),
  47 => 
  array (
    'cat_id' => '41',
    'cat_name' => '儿童床',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '16',
  ),
  48 => 
  array (
    'cat_id' => '51',
    'cat_name' => '书房套装',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  49 => 
  array (
    'cat_id' => '48',
    'cat_name' => '书桌/工作台',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  50 => 
  array (
    'cat_id' => '49',
    'cat_name' => '书柜/书架',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  51 => 
  array (
    'cat_id' => '50',
    'cat_name' => '书椅/转椅',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  52 => 
  array (
    'cat_id' => '55',
    'cat_name' => '办公椅',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  53 => 
  array (
    'cat_id' => '102',
    'cat_name' => '保险箱',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '16',
  ),
  54 => 
  array (
    'cat_id' => '52',
    'cat_name' => '办公沙发',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  55 => 
  array (
    'cat_id' => '56',
    'cat_name' => '会议桌',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  56 => 
  array (
    'cat_id' => '53',
    'cat_name' => '办公桌',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '25',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '办公隔断',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  58 => 
  array (
    'cat_id' => '54',
    'cat_name' => '文件柜',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '13',
  ),
  59 => 
  array (
    'cat_id' => '61',
    'cat_name' => '储物凳',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  60 => 
  array (
    'cat_id' => '58',
    'cat_name' => '折叠餐桌',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  61 => 
  array (
    'cat_id' => '62',
    'cat_name' => '皮墩',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  62 => 
  array (
    'cat_id' => '59',
    'cat_name' => '折叠床',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  63 => 
  array (
    'cat_id' => '60',
    'cat_name' => '储物柜',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  64 => 
  array (
    'cat_id' => '63',
    'cat_name' => '地板',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '11',
  ),
  65 => 
  array (
    'cat_id' => '64',
    'cat_name' => '瓷砖',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  66 => 
  array (
    'cat_id' => '65',
    'cat_name' => '壁纸',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '16',
  ),
  67 => 
  array (
    'cat_id' => '66',
    'cat_name' => '油漆',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '21',
  ),
  68 => 
  array (
    'cat_id' => '67',
    'cat_name' => '楼梯',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  69 => 
  array (
    'cat_id' => '68',
    'cat_name' => '门',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => '15',
  ),
  70 => 
  array (
    'cat_id' => '74',
    'cat_name' => '筒灯',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '18',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '落地灯',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  72 => 
  array (
    'cat_id' => '75',
    'cat_name' => 'LED灯',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
  ),
  73 => 
  array (
    'cat_id' => '72',
    'cat_name' => '吸顶灯',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '39',
  ),
  74 => 
  array (
    'cat_id' => '69',
    'cat_name' => '吊灯',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '18',
  ),
  75 => 
  array (
    'cat_id' => '73',
    'cat_name' => '壁灯',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '13',
  ),
  76 => 
  array (
    'cat_id' => '70',
    'cat_name' => '台灯',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '15',
  ),
  77 => 
  array (
    'cat_id' => '83',
    'cat_name' => '地漏',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '26',
  ),
  78 => 
  array (
    'cat_id' => '80',
    'cat_name' => '浴缸/浴屏',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  79 => 
  array (
    'cat_id' => '77',
    'cat_name' => '橱柜',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  80 => 
  array (
    'cat_id' => '104',
    'cat_name' => '晾衣架',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '花洒',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  82 => 
  array (
    'cat_id' => '78',
    'cat_name' => '橱盆/水槽',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '33',
  ),
  83 => 
  array (
    'cat_id' => '82',
    'cat_name' => '浴霸',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '21',
  ),
  84 => 
  array (
    'cat_id' => '79',
    'cat_name' => '龙头/手阀',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  85 => 
  array (
    'cat_id' => '76',
    'cat_name' => '吊顶',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  86 => 
  array (
    'cat_id' => '103',
    'cat_name' => '座便',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '电线',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '14',
  ),
  88 => 
  array (
    'cat_id' => '84',
    'cat_name' => '开关插座',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '108',
  ),
  89 => 
  array (
    'cat_id' => '85',
    'cat_name' => '拉手',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  90 => 
  array (
    'cat_id' => '86',
    'cat_name' => '锁具',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '27',
  ),
  91 => 
  array (
    'cat_id' => '93',
    'cat_name' => '电风扇',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  92 => 
  array (
    'cat_id' => '90',
    'cat_name' => '电磁炉',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  93 => 
  array (
    'cat_id' => '100',
    'cat_name' => '抽烟机',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  94 => 
  array (
    'cat_id' => '91',
    'cat_name' => '空调',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  95 => 
  array (
    'cat_id' => '88',
    'cat_name' => '热水器',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  96 => 
  array (
    'cat_id' => '101',
    'cat_name' => '消毒柜/洗碗柜',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  97 => 
  array (
    'cat_id' => '92',
    'cat_name' => '吸尘器',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  98 => 
  array (
    'cat_id' => '89',
    'cat_name' => '燃气灶',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  99 => 
  array (
    'cat_id' => '96',
    'cat_name' => '防水材料',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  100 => 
  array (
    'cat_id' => '97',
    'cat_name' => '沙石料',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  101 => 
  array (
    'cat_id' => '94',
    'cat_name' => '板材',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '25',
  ),
  102 => 
  array (
    'cat_id' => '95',
    'cat_name' => '管材',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '20',
  ),
);
?>